<?php

namespace INHack20\ConsultorioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DiarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiarioRepository extends EntityRepository
{
    public function findToday(){
        $fecha = new \DateTime();
        return $this->getEntityManager()
                ->createQuery("SELECT d FROM INHack20ConsultorioBundle:Diario d WHERE d.fechaCreado LIKE '".$fecha->format('Y-m-d')."%' ORDER BY d.fechaCreado ASC")
            ->getResult();
    }
}
