<?php

namespace INHack20\ConsultorioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteRepository extends EntityRepository
{
    public function findToday(){
        $fecha = new \DateTime();
        return $this->getEntityManager()
                ->createQuery("SELECT p FROM INHack20ConsultorioBundle:Paciente p WHERE p.fechaCreado LIKE '".$fecha->format('Y-m-d')."%' ORDER BY p.fechaCreado ASC")
            ->getResult();
    }
}
